// <auto-generated />
using System;
using JurcauIulia_Pizzerie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JurcauIulia_Pizzerie.Migrations
{
    [DbContext(typeof(JurcauIulia_PizzerieContext))]
    [Migration("20220106200849_AluatPizza")]
    partial class AluatPizza
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JurcauIulia_Pizzerie.Models.Aluat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipAluat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Aluat");
                });

            modelBuilder.Entity("JurcauIulia_Pizzerie.Models.AluatPizza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AluatID")
                        .HasColumnType("int");

                    b.Property<int>("PizzaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AluatID");

                    b.HasIndex("PizzaID");

                    b.ToTable("AluatPizza");
                });

            modelBuilder.Entity("JurcauIulia_Pizzerie.Models.Pizza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataPlasareComanda")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Incrediente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PizzerieID")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.HasIndex("PizzerieID");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("JurcauIulia_Pizzerie.Models.Pizzerie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumePizzerie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pizzerie");
                });

            modelBuilder.Entity("JurcauIulia_Pizzerie.Models.AluatPizza", b =>
                {
                    b.HasOne("JurcauIulia_Pizzerie.Models.Aluat", "Aluat")
                        .WithMany("BookCategories")
                        .HasForeignKey("AluatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JurcauIulia_Pizzerie.Models.Pizza", "Pizza")
                        .WithMany("AluatPizzas")
                        .HasForeignKey("PizzaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluat");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("JurcauIulia_Pizzerie.Models.Pizza", b =>
                {
                    b.HasOne("JurcauIulia_Pizzerie.Models.Pizzerie", "Pizzerie")
                        .WithMany("Pizzas")
                        .HasForeignKey("PizzerieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizzerie");
                });

            modelBuilder.Entity("JurcauIulia_Pizzerie.Models.Aluat", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("JurcauIulia_Pizzerie.Models.Pizza", b =>
                {
                    b.Navigation("AluatPizzas");
                });

            modelBuilder.Entity("JurcauIulia_Pizzerie.Models.Pizzerie", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
